1. (10 Points) Write a Python/NumPy code block that finds the distinct/unique common items between these two arrays:
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])
Your output should contain only the distinct overlapping values. For example, if a 2 is found in both array a and array b, your output should contain only one 2 even if array a contains more than one 2 within it.

In [1]:
import numpy as np
import pandas

In [3]:
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6]) #question1
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8]) 
c = np.unique(np.intersect1d(a, b))#get their intersection and remove the repeat
print(c)

[2 4]


2. (10 Points) Create the following 5x3 array using knowledge you have of Python’s / NumPy’s sequencing functionality so that you do not need to explicitly key in every integer value.

In [4]:
array53 = np.arange(1, 16).reshape(3, 5).T#question2
print(array53)

[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]


3. (10 Points) The process of transforming a multidimensional array into a unidimensional array is referred to as “flattening”. Transform the 5x3 array shown above in Problem 2 into a unidimensional array such that the sequence of values contained within the array is as follows: 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15


In [5]:
flarray53 = array53.T.flatten()#question3
print(flarray53)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


4. (15 Points) Transform the 2-D array shown in Problem 2 into a 3 dimensional array such that the first column becomes the first dimension of the 3-D array, the second column becomes the second dimension of the 3-D array, and the third column becomes the third dimension of the 3-D array.

In [6]:
d2tod3 = np.reshape(array53.T, (3,1,5))#question4
print(d2tod3)

[[[ 1  2  3  4  5]]

 [[ 6  7  8  9 10]]

 [[11 12 13 14 15]]]


5. (15 Points) Transform the 3-D array you created in Problem 4 back to the 2-dimensional format shown in Problem 2.

In [7]:
d3tod2 = np.reshape(d2tod3, (3, 5)).T#question5
print(d3tod2)

[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]


6. (10 Points) You are given the following two arrays:
a = np.array([12, 5, 7, 15, 3, 1, 8])
b = np.array([14, 6, 3, 11, 19, 12, 5])
Write a Python/Numpy code block that removes from array a any items that are also present in array b.

In [2]:
a = np.array([12, 5, 7, 15, 3, 1, 8]) #question6
b = np.array([14, 6, 3, 11, 19, 12, 5])
np.setdiff1d(a, b)

array([ 1,  7,  8, 15])

7. (30 Points) For this problem you will load a small data set to your online GitHub repository and then read it into a NumPy 2D array. You will then use the content that NumPy array to answer a series of analytical questions.

In [9]:
np.set_printoptions(suppress = True)
nyc_water = pandas.read_csv('https://raw.githubusercontent.com/NewThread-ZY/AIM-5001/master/Module6_Data.csv').to_numpy()
print(nyc_water)
print(nyc_water.shape)

[[   1979.  7102100.     1512.      213. ]
 [   1980.  7071639.     1506.      213. ]
 [   1981.  7089241.     1309.      185. ]
 [   1982.  7109105.     1382.      194. ]
 [   1983.  7181224.     1424.      198. ]
 [   1984.  7234514.     1465.      203. ]
 [   1985.  7274054.     1326.      182. ]
 [   1986.  7319246.     1351.      185. ]
 [   1987.  7342476.     1447.      197. ]
 [   1988.  7353719.     1484.      202. ]
 [   1989.  7344175.     1402.      191. ]
 [   1990.  7335650.     1424.      194. ]
 [   1991.  7374501.     1469.      199. ]
 [   1992.  7428944.     1369.      184. ]
 [   1993.  7506166.     1368.5     182. ]
 [   1994.  7570458.     1357.7     179. ]
 [   1995.  7633040.     1325.7     174. ]
 [   1996.  7697812.     1297.9     169. ]
 [   1997.  7773443.     1205.5     155. ]
 [   1998.  7858259.     1219.5     155. ]
 [   1999.  7947660.     1237.2     156. ]
 [   2000.  8008278.     1240.4     155. ]
 [   2001.  8024963.5    1184.      148. ]
 [   2002. 

1.What is the maximum yearly NYC consumption of water in millions of gallons per day?

In [10]:
yearlycomsum = nyc_water[:nyc_water.shape[0], 2:3]#question1
print('The maximum yearly NYC consumption of water in millions of gallons per day is '+str(yearlycomsum.max()))

The maximum yearly NYC consumption of water in millions of gallons per day is 1512.0


2.How many calendar years are represented within this data set? NumPy's shape command is one way to find out.

In [11]:
calendaryears = np.unique(nyc_water[:nyc_water.shape[0], 0:1])#question2
print('There is '+str(calendaryears.shape[0])+' calendar years')

There is 39 calendar years


3.What is the mean and the standard deviation of the per capita daily water consumption?

In [12]:
percapitadailywater = nyc_water[:nyc_water.shape[0], 3:4]#question3
pcd_mean = np.mean(percapitadailywater)
pcd_std = np.std(percapitadailywater)#One of the method to calculate standard deviation
pcd_st = np.sqrt(np.var(percapitadailywater))#Other method to calculate standard deviation
print('The mean of the per capita daily water consumption is '+str(pcd_mean))
print('The standard deviation of the per capita daily water consumption is '+str(pcd_std))

The mean of the per capita daily water consumption is 160.30769230769232
The standard deviation of the per capita daily water consumption is 31.51894330370624


4.What is the increase or decrease in population from year to year? Use NumPy's `diff` function to create an array of differences and save that to a variable called "pop_diff", then print that variable to the screen.

In [13]:
population = nyc_water[:nyc_water.shape[0], 1:2].flatten()#question4
pop_diff = np.diff(population)
print(pop_diff)

[-30461.   17602.   19864.   72119.   53290.   39540.   45192.   23230.
  11243.   -9544.   -8525.   38851.   54443.   77222.   64292.   62582.
  64772.   75631.   84816.   89401.   60618.   16685.5  16685.5  16685.5
  16685.5  16685.5  16685.5  16685.5  16685.5  16685.5  16685.5 108965.
  77081.   61281.   49530.   44512.   21171.   85025. ]
